authors:
  aebruno:
    name: Andrew E. Bruno
    description: Lead Developer
    avatar: https://avatars.githubusercontent.com/u/105232
    url: https://github.com/aebruno
  dsajdak:
    name: Dori Sajdak 
    description: Project Manager
    avatar: https://avatars.githubusercontent.com/u/9355962
    url: https://github.com/dsajdak
